### ISSUE TITLE
hmr insits on finding a DOM node even for Platform.worker modules

### ISSUE THREAD

**Issue by baffalop** [NoRedInk/jetpack#92]
I'm not sure if I'm off the mark here, but I was running into this issue with Parcel, who directed me to `rtfeldman/node-elm-compiler`, but then through a Github code search it's here that I find a match for the source that I was seeing when I traced the error.

In short, I'm using a `Platform.worker` Elm module in a service worker. It's dealing with dynamically generating a subset of resources that I'm caching for my PWA. When testing the app through the Parcel dev server, I was getting a `ReferenceError: document is not defined` which traced to the following function:

```js
function wrapPublicModule(path, module) {
    var originalInit = module.init;
    if (originalInit) {
        module.init = function (args) {
            var elm;
            var portSubscribes = {};
            var portSends = {};
            var domNode = null;
            var flags = null;
            if (typeof args !== 'undefined') {
                // normal case
                domNode = args['node'] && !isFullscreenApp()
                    ? wrapDomNode(args['node'])
                    : document.body;
                flags = args['flags'];
            } else {
                // rare case: Elm allows init to be called without any arguments at all
                domNode = document.body;
                flags = undefined
            }
            initializingInstance = registerInstance(domNode, flags, path, portSubscribes, portSends);
            elm = originalInit(args);
            wrapPorts(elm, portSubscribes, portSends);
            initializingInstance = null;
            return elm;
        };
    } else {
        console.error("Could not find a public module to wrap at path " + path)
    }
}
```

You'll recognise this from `resources/hmr.js`. You can see that underneath the comment about "rare case", it still attempts to get a dummy DOM node, which breaks in the context of a service worker where there is no `document`. It seems that a DOM node is required as a parameter for `registerInstance` and after that I'm not sure how deep it goes.

Like I said, I'm not sure if there is a dependency from this, via `node-elm-compiler`, to Parcel, but this is the only place where I've found this code verbatim so I thought I'd raise the issue here. Am I on the right track?

**Comment by stoeffel** [comment]
AFAIK there is no dependency from this to node-elm-compiler and also no relation to Parcel. hmr.js in this project was copied from https://github.com/fluxxu/elm-hot-loader maybe Parcel is using that?
